lang: zh-CN
timezone: Asia/Shanghai
url: "https://runchengxie.github.io"
baseurl: ""
title: Runcheng
logo: /assets/img/logo.png
description: 记录我在投资和生活中的思考

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
